### ISSUE TITLE
Installation fails in python 3

### ISSUE THREAD

**Issue by jordeu** [mpschr/mutex#1]
If you try to install mutex in python 3 it fails due to the dependency with the package "multiprocessing". Multiprocessing is part of python 3 and the package "multiprocessing" is a python 2 backport.

You can reproduce like this:
1. Create a conda environment:
   $ conda create -n mutex python=3 pandas joblib scipy
2. Install mutex
   $ pip install git+https://github.com/mpschr/mutex.git

The solution is to remove the "multiprocessing" from the install_requires

**Comment by mpschr** [comment]
Ok, removed it from setup.py - untested and edited on github directly. Thanks!

**Comment by jordeu** [comment]
Perfect! Now the installation it's working under python3. And I've also tested the first example in the notebook.
